version: '3.7'

services:
  run-up-admin:
    container_name: front-end
    restart: always
    build: .
    environment:
      PORT: 80
      PUBLIC_URL: https://36yearold.baby
      VIRTUAL_HOST: 36yearold.baby
      LETSENCRYPT_HOST: 36yearold.baby
      LETSENCRYPT_EMAIL: hello@jackallen.me
    expose:
      - 80
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
    name: proxy-network
